version: '3.8'
services:
  stats-server:
    build: stats-server
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db


  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=java

  ewm-service:
    build: ewm-service
    container_name: ewm-service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=java
