CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255)                           NOT NULL,
    uri VARCHAR(512)                           NOT NULL,
    ip VARCHAR(512)                            NOT NULL,
    created timestamp without time zone        NOT NULL,
    CONSTRAINT pk_hitss PRIMARY KEY (id)
);









